//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarksEntity
    {
        public int Id { get; set; }
        public int Lesson { get; set; }
        public decimal Mark { get; set; }
    }
}
