//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTable
    {
        public int Id { get; set; }
        public Nullable<int> TaskNo { get; set; }
        public string TaskText { get; set; }
    }
}
